### ISSUE TITLE
Maybe we can merge efforts together?

### ISSUE THREAD

**Issue by ergo** [wizeline/sqlalchemy-pagination#2]
There is already working cross framework pagination library called "paginate" (earlier it was part of webhelpers project as webhelpers.paginate module), it can be found it here.

https://github.com/Pylons/paginate + https://pypi.python.org/pypi/paginate_sqlalchemy

It can work with multiple datasources, maybe it would make sense to work on improving its codebase with us than start from scratch?

**Comment by albertein** [comment]
@ergo I appreciate you reaching out. To be honest, we got to see the paginate library before writing this one and we decided to build a very simplistic paginator that avoids dealing with serialization. Happy to discuss with my team if you have some ideas for collaboration.

**Comment by ergo** [comment]
Hey @albertein, sure, I'm not really sure what do you mean by "serialization" to be honest (Maybe you looked at other lib with similar name)?

As you can see here: https://github.com/Pylons/paginate_sqlalchemy/blob/master/paginate_sqlalchemy/__init__.py

Both by default use same limit/offset strategy. Paginate allows to easly build wrappers for other types of storage, for example I was using an elasticsearch plugin with it.

**Comment by albertein** [comment]
@ergo I'm sorry for the misunderstanding and for taking too long to get back to you again, I was glancing at https://github.com/Pylons/paginate instead of https://github.com/Pylons/paginate_sqlalchemy/ and looked like it did a little too much. 

Anyways, we need the output format exactly as it is on this repo, and even when we could transform when using it this is intended mostly for our internal usage, and decided to make it public in case it might be helpful for someone else.

**Comment by ergo** [comment]
@albertein Sure, thanks for your answer. The more libs in the ecosystem the more code we can share and learn from each other. Good luck!
